# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05467dcb8e52b05864afccd2b58e117d2c39db5650f9f45b4e7ee240f16fee16877945f77fd78af15686897f95f20f73f64f1379c952e8e5b5268331ba59d98b

test:
  secret_key_base: d7df9a5d4c55df84a3e5967dba87e526e2a90689b3552516f8686ee427cf17f7fda743e649e3c5a373a3e59b0020a585cd6c3bed94f05fde6ab27691a89f8f28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
